'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { calculateAll, defaults } from '@/lib/engine';
import { exportCsv } from '@/lib/csv';
import type { AppDataset, Recommendation, Settings } from '@/lib/types';

const fmt=(n:number|null,digits=0)=>n===null?'—':n.toLocaleString('ru-RU',{maximumFractionDigits:digits});
const urgencyLabels={critical:'Критично',high:'Скоро закончится',planned:'Плановый заказ',covered:'Запас достаточен',review:'Проверить данные'};
const monthLabel=(m:string)=>new Date(m+'-01T00:00:00Z').toLocaleDateString('ru-RU',{month:'short',year:'2-digit',timeZone:'UTC'});
function Icon({name,size=20}:{name:string;size?:number}){
  const paths:Record<string,React.ReactNode>={
    grid:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,
    box:<><path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="M3 8v9l9 5 9-5V8M12 13v9M7.5 5.5l9 5V15"/></>,
    chart:<><path d="M4 3v17h17M7 14l4-5 4 3 6-8"/></>,
    files:<><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 8h6M9 12h6M9 16h4"/></>,
    search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,
    download:<><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></>,
    tune:<><path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/></>,
    arrow:<path d="M5 12h14m-5-5 5 5-5 5"/>,
    alert:<><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v1"/></>,
    check:<path d="m5 12 4 4L19 6"/>,
    close:<path d="m6 6 12 12M6 18 18 6"/>,
    refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 3M4 16l2 3a7 7 0 0 0 12-2"/></>,
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.box}</svg>;
}
function DemandChart({rows}:{rows:Recommendation[]}){
  const months=[...new Set(rows.flatMap(r=>r.history.map(m=>m.month)))].sort();
  const points=months.map(month=>({month,value:rows.reduce((s,r)=>s+(r.history.find(m=>m.month===month)?.regular??0),0),forecast:false}));
  const future=[...new Set(rows.flatMap(r=>r.forecastMonths.map(m=>m.month)))].sort();
  points.push(...future.map(month=>({month,value:rows.reduce((s,r)=>s+(r.forecastMonths.find(m=>m.month===month)?.quantity??0),0),forecast:true})));
  const max=Math.max(1,...points.map(p=>p.value));
  return <div className="chart" role="img" aria-label="Регулярный месячный спрос и прогноз. Текущий неполный месяц исключён.">
    <div className="chart-scale"><span>{fmt(max)}</span><span>{fmt(max/2)}</span><span>0</span></div>
    <div className="chart-bars">{points.map(p=><div className="chart-column" key={p.month}><div className="bar-track"><div title={`${monthLabel(p.month)}: ${fmt(p.value,1)}`} className={`bar ${p.forecast?'forecast-bar':''}`} style={{height:`${Math.max(1,p.value/max*100)}%`}}/></div><span>{monthLabel(p.month)}</span></div>)}</div>
  </div>;
}
function Details({row,onClose}:{row:Recommendation|null;onClose:()=>void}){
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{if(row&&!ref.current?.open)ref.current?.showModal();if(!row&&ref.current?.open)ref.current?.close();},[row]);
  return <dialog ref={ref} className="details-dialog" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-labelledby="detail-title">
    {row&&<><div className="detail-header"><div><p className="eyebrow">РАСЧЁТ БЕЗ ЧЁРНОГО ЯЩИКА</p><h2 id="detail-title">{row.sku||row.code}</h2><p>{row.name}</p><small>Код 1С: {row.code} · Категория: {row.category??'нет данных'}</small></div><button className="icon-button" aria-label="Закрыть детали" onClick={onClose}><Icon name="close"/></button></div>
    <div className="detail-body"><div className="formula-result"><div><span>Рекомендованный заказ</span><strong>{fmt(row.order)} <small>шт.</small></strong></div><span className={`badge ${row.urgency}`}>{urgencyLabels[row.urgency]}</span></div>
      <div className="calculation-steps">
        {[['01','Регулярный спрос',`${fmt(row.baseline,2)} шт./мес.`,`${row.validMonths} полных месяцев; отрицательные значения ограничены нулём, IQR — по настройке.`],['02','Рост и сезонность',`× ${fmt(row.growthFactor,3)} × ${fmt(row.seasonFactor,3)}`,'Рост ограничен 0,5–1,5; сезонность 0,7–1,3.'],['03','Прогноз на горизонт',`${fmt(row.forecast,2)} шт.`,row.forecastMonths.map(m=>`${monthLabel(m.month)}: ${fmt(m.quantity,1)}`).join(' · ')],['04','Вычет доступного запаса',`${fmt(row.forecast,2)} − ${fmt(row.stock)} − ${fmt(row.transit)}`,'Свободный остаток и товар в пути из TDSheet. Резерв повторно не вычитается.'],['05','Округление заказа',row.order===null?'Нужна проверка':`${fmt(row.netNeed,2)} → ${fmt(row.order)} шт.`,`Округление вверх до кратности ${fmt(row.multiple)}. Это не минимальный заказ.`]].map(([n,title,value,description])=><div className="step" key={n}><span>{n}</span><div><h4>{title}</h4><p>{description}</p></div><strong>{value}</strong></div>)}
      </div>
      <h3>История и прогноз</h3><DemandChart rows={[row]}/>
      <div className="detail-facts"><span>Операций: <b>{fmt(row.transactionCount)}</b></span><span>IQR-порог: <b>{fmt(row.iqrThreshold,2)}</b></span><span>Аномалий в базе: <b>{row.anomalyCount}</b></span></div>
      <details><summary>Исходные месячные продажи и обработка</summary><div className="table-scroll"><table><thead><tr><th>Месяц</th><th>Исходное</th><th>После очистки</th><th>Регулярное</th></tr></thead><tbody>{row.history.map(m=><tr key={m.month}><td>{monthLabel(m.month)}</td><td>{fmt(m.raw)}</td><td>{fmt(m.cleaned)}{m.assumedZero?' *':''}</td><td>{fmt(m.regular,2)}</td></tr>)}</tbody></table></div><small>* Пустое значение принято за ноль по настройке сценария.</small></details>
      <div className="explanation"><h3>Что учтено</h3><ul>{row.notes.map((note,i)=><li key={i}>{note}</li>)}<li>Текущий неполный месяц исключён. Прогноз начинается со следующего месяца.</li><li>AP/AQ не используются. Lead time и минимальный заказ не заданы.</li></ul></div>
      <details><summary>Источники товара</summary><ul className="source-list">{row.sources.map(s=><li key={s}>{s}</li>)}</ul></details>
    </div></>}
  </dialog>;
}
export default function Dashboard(){
  const [data,setData]=useState<AppDataset|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
  const [settings,setSettings]=useState<Settings>(defaults),[showSettings,setShowSettings]=useState(false);
  const [view,setView]=useState('overview'),[search,setSearch]=useState(''),[urgency,setUrgency]=useState('all'),[page,setPage]=useState(1),[selected,setSelected]=useState<string|null>(null),[sort,setSort]=useState('priority');
  async function reload(){setLoading(true);setError('');try{const response=await fetch('/api/data',{cache:'no-store'});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setData(payload);}catch(e){setError(e instanceof Error?e.message:'Ошибка загрузки');}finally{setLoading(false);}}
  useEffect(()=>{void reload();},[]);
  const rows=useMemo(()=>data?calculateAll(data,settings):[],[data,settings]);
  const filtered=useMemo(()=>{const query=search.toLocaleLowerCase().trim();const list=rows.filter(r=>(urgency==='all'||r.urgency===urgency)&&(!query||`${r.sku} ${r.code} ${r.name}`.toLocaleLowerCase().includes(query)));return sort==='sku'?[...list].sort((a,b)=>(a.sku||a.code).localeCompare(b.sku||b.code)):sort==='order'?[...list].sort((a,b)=>(b.order??-1)-(a.order??-1)):list;},[rows,search,urgency,sort]);
  useEffect(()=>setPage(1),[search,urgency,sort,settings]);
  const currentRow=rows.find(r=>r.code===selected)??null, pages=Math.max(1,Math.ceil(filtered.length/20)),safePage=Math.min(page,pages);
  const orders=rows.filter(r=>(r.order??0)>0),critical=rows.filter(r=>r.urgency==='critical'||r.urgency==='high'),review=rows.filter(r=>r.urgency==='review'),anomalies=rows.filter(r=>r.anomalyCount>0);
  function download(){if(!data)return;const blob=new Blob([exportCsv(filtered,settings,data.asOf)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`stockpilot-orders-${data.asOf}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  const set=<K extends keyof Settings>(key:K,value:Settings[K])=>setSettings(old=>({...old,[key]:value}));
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="/" aria-label="StockPilot AI — главная"><span className="brand-symbol"><Icon name="box" size={25}/></span><span>StockPilot<span className="ai">AI</span></span></a><p className="workspace-label">ПЛАНИРОВАНИЕ ЗАКУПОК</p>
      <nav aria-label="Основная навигация">{[['overview','grid','Обзор'],['orders','box','Рекомендации'],['sources','files','Источники данных']].map(([id,icon,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}><Icon name={icon}/>{label}{id==='orders'&&data&&<span className="nav-count">{orders.length}</span>}</button>)}</nav>
      <div className="sidebar-note"><span className="live-dot"/><b>Локальные данные</b><p>Excel остаются на вашем компьютере. Прозрачный расчёт для каждого SKU.</p></div><div className="team"><span>NT</span><div>N Turbo<small>Hackathon workspace</small></div><span className="team-dot">●</span></div>
    </aside>
    <main><header className="topbar"><div className="breadcrumb">Рабочее пространство <span>/</span> <b>Systeme Electric</b></div><div className="topbar-right"><span className="local-badge"><span className="live-dot"/>Локальный режим</span><span className="avatar">NT</span></div></header>
      <div className="main-content"><section className="page-heading"><div><p className="eyebrow">SUPPLY INTELLIGENCE</p><h1>{view==='sources'?'Данные, которым можно доверять':view==='orders'?'Рекомендации к заказу':'Запасы под контролем.'}</h1><p>{view==='sources'?'Источники, ограничения и правила расчёта.':'От Excel к обоснованному заказу — с объяснением каждого решения.'}</p></div><button className="secondary" onClick={()=>void reload()} disabled={loading}><Icon name="refresh"/>{loading?'Импорт…':'Обновить данные'}</button></section>
      {error&&<div role="alert" className="error-panel"><Icon name="alert"/><div><b>Не удалось импортировать данные</b><p>{error}</p><p>Проверьте наличие шести исходных Excel в data/raw и повторите загрузку.</p></div></div>}
      {loading&&!data&&<div className="loading-panel" role="status"><div className="spinner"/><h2>Собираем картину спроса</h2><p>Читаем локальные Excel, связываем Код 1С и проверяем историю операций.</p></div>}
      {data&&<><div className="data-strip"><span><span className="live-dot"/>{data.files.length} Excel подключены</span><span>Данные на {data.asOf.split('-').reverse().join('.')}</span><span>{fmt(data.transactionCount)} операций</span><span className="strip-right">Прогноз со следующего месяца</span></div>
      {view==='sources'?<><div className="source-grid">{data.files.map((f,i)=><article className="source-card" key={f.name}><span className="file-icon"><Icon name="files"/></span><small>ИСТОЧНИК {String(i+1).padStart(2,'0')}</small><h3>{f.name}</h3><p>{f.sheets.join(' · ')}</p><span className="source-status"><Icon name="check" size={14}/> Прочитан локально</span></article>)}</div><section className="panel methodology"><h2>Правила, которые можно проверить</h2><p>Основной ключ — Код 1С. Кратность — MOQ-файл. Спрос — отдельный месячный отчёт. Свободный остаток, товар в пути и категория — TDSheet.</p><ul>{data.warnings.map(w=><li key={w}>{w}</li>)}</ul><p>IQR строится по положительным строкам расходных накладных за 24 завершённых месяца, минимум 8 наблюдений. Крупная операция не считается отдельным клиентом. Доля превышения порога уменьшает соответствующий месячный спрос; это приближение из-за расхождений источников.</p><p>Пустые месяцы принимаются за ноль только при включённой настройке. Неизвестный остаток не становится нулём. Прогноз — объяснимый статистический сценарий, без внешней LLM и без автоматической отправки заказов.</p><button className="secondary" onClick={()=>{setView('overview');setShowSettings(true);}}>Открыть настройки расчёта <Icon name="arrow"/></button></section></>:<>
        <section className="kpi-grid"><article className="kpi"><div>К заказу <span className="kpi-icon"><Icon name="box"/></span></div><strong>{fmt(orders.length)}<small> SKU</small></strong><p>{fmt(orders.reduce((s,r)=>s+(r.order??0),0))} единиц с учётом кратности</p></article><article className="kpi"><div>Требуют внимания <span className="kpi-icon warm"><Icon name="alert"/></span></div><strong>{fmt(critical.length)}<small> SKU</small></strong><p><span className="orange-dot"/> Нулевой или низкий свободный запас</p></article><article className="kpi"><div>Прогноз спроса <span className="kpi-icon"><Icon name="chart"/></span></div><strong>{fmt(rows.reduce((s,r)=>s+r.forecast,0))}<small> шт.</small></strong><p>Горизонт: {settings.horizon} мес. · не срок поставки</p></article><article className="kpi"><div>Аномалии спроса <span className="kpi-icon purple"><Icon name="chart"/></span></div><strong>{fmt(anomalies.length)}<small> SKU</small></strong><p>IQR · {settings.anomalies?'коррекция включена':'только обнаружение'}</p></article></section>
        <section className="scenario-bar"><div><Icon name="tune"/><b>Сценарий заказа</b><span>Горизонт</span><select aria-label="Горизонт прогноза" value={settings.horizon} onChange={e=>set('horizon',Number(e.target.value))}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} мес.</option>)}</select></div><button className="text-button" onClick={()=>setShowSettings(v=>!v)} aria-expanded={showSettings}>{showSettings?'Скрыть настройки':'Настроить расчёт'} <Icon name="tune" size={16}/></button></section>
        {showSettings&&<section className="settings-panel"><div className="setting-toggles">{[['growth','Рост год к году','Последние 3 полных месяца; пределы ×0,5–1,5'],['seasonality','Общая сезонность','Полные 2024–2025 годы; пределы ×0,7–1,3'],['anomalies','Коррекция IQR','Уменьшить влияние необычно крупных операций'],['blankAsZero','Пустые месяцы → 0','Явное допущение; выключите для исключения пропусков']].map(([key,label,hint])=><label className="setting" key={key}><input type="checkbox" checked={settings[key as 'growth']} onChange={e=>set(key as 'growth',e.target.checked)}/><span><b>{label}</b><small>{hint}</small></span></label>)}</div><div className="stockout-setting"><label htmlFor="stockout">Ручная компенсация stockout <b>{settings.stockoutPercent}%</b></label><input id="stockout" type="range" min="0" max="50" step="5" value={settings.stockoutPercent} onChange={e=>set('stockoutPercent',Number(e.target.value))}/><small>0% — отключена. Интервалов отсутствия нет; это сценарное допущение.</small></div><button className="text-button" onClick={()=>setSettings(defaults)}>Сбросить настройки</button></section>}
        {view==='overview'&&<section className="insight-grid"><article className="panel trend-panel"><div className="panel-heading"><div><h2>Спрос и горизонт планирования</h2><p>12 завершённых месяцев → прогноз</p></div><div className="legend"><span><i/>Регулярный спрос</span><span><i className="teal"/>Прогноз</span></div></div><DemandChart rows={rows}/></article><article className="insight-card"><span className="insight-tag"><Icon name="check" size={16}/> ОБЪЯСНИМЫЙ РАСЧЁТ</span><h2>Заказывать нужное.<br/>Понимать почему.</h2><p>Спрос очищен от отрицательных значений. Крупные операции проверены IQR. Остатки и поставки учтены отдельно.</p><div className="quality-line"><b>{review.length}</b><span>SKU требуют проверки данных<br/>Заказ для них не сформирован</span></div><button onClick={()=>{setUrgency('review');setView('orders');}} className="insight-link">Проверить исключения <Icon name="arrow" size={18}/></button></article></section>}
        <section className="panel orders-panel"><div className="panel-heading"><div><p className="eyebrow">RECOMMENDED ORDERS</p><h2>Рекомендации к заказу <span className="count-pill">{filtered.length}</span></h2></div><button className="primary" onClick={download} disabled={!filtered.length}><Icon name="download" size={17}/>Экспорт CSV</button></div><div className="table-controls"><div className="search"><Icon name="search" size={18}/><input placeholder="Поиск по SKU, названию или Коду 1С" aria-label="Поиск SKU" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Очистить поиск" onClick={()=>setSearch('')}><Icon name="close" size={16}/></button>}</div><select aria-label="Фильтр срочности" value={urgency} onChange={e=>setUrgency(e.target.value)}><option value="all">Любая срочность</option>{Object.entries(urgencyLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="Сортировка" value={sort} onChange={e=>setSort(e.target.value)}><option value="priority">По приоритету</option><option value="order">По объёму заказа</option><option value="sku">По артикулу</option></select></div><div className="demo-chips"><span>Быстрая проверка:</span>{['ATN000343','BLNZA000011','U734M'].map(sku=><button key={sku} onClick={()=>{setSearch(sku);setUrgency('all');}}>{sku}<Icon name="arrow" size={12}/></button>)}</div>
        <div className="table-scroll"><table className="orders-table"><thead><tr><th>Товар / SKU</th><th>Прогноз <small>шт.</small></th><th>Остаток</th><th>В пути</th><th>К заказу</th><th>Срочность</th><th><span className="sr-only">Детали</span></th></tr></thead><tbody>{filtered.slice((safePage-1)*20,safePage*20).map(r=><tr key={r.code}><td><button className="product-button" onClick={()=>setSelected(r.code)}><span className="sku">{r.sku||r.code}{r.anomalyCount>0&&<span className="anomaly-mark" title={`${r.anomalyCount} аномалий IQR`} aria-label={`${r.anomalyCount} аномалий IQR`}>IQR</span>}</span><span className="product-name" title={r.name}>{r.name}</span><small>{r.code} · кратность {fmt(r.multiple)}</small></button></td><td>{fmt(r.forecast,1)}</td><td>{fmt(r.stock)}</td><td>{fmt(r.transit)}</td><td><strong className={(r.order??0)>0?'order-value':''}>{fmt(r.order)}</strong></td><td><span className={`badge ${r.urgency}`}>{urgencyLabels[r.urgency]}</span></td><td><button className="icon-button" aria-label={`Детали ${r.sku||r.code}`} onClick={()=>setSelected(r.code)}><Icon name="arrow" size={18}/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state"><Icon name="search" size={30}/><h3>Товары не найдены</h3><p>Измените запрос или фильтр срочности.</p><button className="secondary" onClick={()=>{setSearch('');setUrgency('all');}}>Сбросить фильтры</button></div>}</div><div className="pagination"><span>{filtered.length?`${(safePage-1)*20+1}–${Math.min(safePage*20,filtered.length)}`:'0'} из {filtered.length} SKU</span><div><button disabled={safePage===1} onClick={()=>setPage(safePage-1)} aria-label="Предыдущая страница">←</button><span>{safePage} / {pages}</span><button disabled={safePage===pages} onClick={()=>setPage(safePage+1)} aria-label="Следующая страница">→</button></div><small>— = нет подтверждённых данных</small></div></section>
      </>}<footer>StockPilot AI <span>Объяснимое планирование · N Turbo</span><span>Расчётный сценарий, не отправленный заказ</span></footer></>}
      </div>
    </main><Details row={currentRow} onClose={()=>setSelected(null)}/>
  </div>;
}
